- hosts: all
  remote_user: root
  roles:
    - common

- hosts: gitlab_runners
  remote_user: root
  roles:
    - docker
    - gitlab_runner

- hosts: docker
  remote_user: root
  roles:
    - docker
