- name: install gdebi
  apt:
    state: present
    name: gdebi-core


- name: Get the archive of RStudio Server
  get_url:
    url: https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.5033-amd64.deb
    dest: /tmp/rstudio.deb
  become: no

- name: Install RStudio Server
  command: /usr/bin/gdebi --non-interactive /tmp/rstudio.deb

